name: "Terraform infra folders"

on:
  push:
    paths:
      - terraform/folders/**

jobs:
  tf-folders:
    environment: development
    strategy:
      matrix:
        dirs: [{
                "path": "folders",
                "prefix": "terraform2/state/gcp_folder"
              }]
    uses: ./.github/workflows/terraform-workflow.yml
    with:
      workingdirectory: ${{ matrix.dirs.path }}
      backendgcpprefix: ${{ matrix.dirs.prefix }}
